### PR TITLE
feature: deep copy of array #hacktoberfest

### PR DESCRIPTION
**Pull request by igrzhukovich**
function for deep copy of array

### CODE REVIEW

**Comment by Hetarth02** [comment]
@igrzhukovich I appreciate the PR but the method to create deep copy has some limitations to it. If you could update the function logic that would be much better else if it is too complex for you update the doc comment with the limitations.
To know about the limitations of your logic do refer to this [article](https://dev.to/samanthaming/how-to-deep-clone-an-array-in-javascript-3cig).

**Comment by igrzhukovich** [comment]
@Hetarth02 Thanks for help. Updated

**Comment by Hetarth02** [comment]
@igrzhukovich The code doesn't seem to follow the conventions used in the package. Please assure that it follows the proper code structure to assure there aren't any breaking changes being deployed.

**Comment by Hetarth02** [comment]
If you find it difficult, let me know and I will help you if I can.

**Pull request merged**
