### PR TITLE
added functions for rotating and reversing array in parts

### PR DESCRIPTION
**Pull request by Nirbhayparmar**
- New function name- array_rotate and array_reverse_part
- Short Description
  - array_rotate function can rotate array in counter clockwise direction (left) by given number of steps
  - array_reverse_part function can reverse specific part of the array like last two element or any subarray
- References (documentation, links, etc.)
  - I took this idea from a GFG question or rotating array 
- Limitations (If it has any edge cases)
  - Currently this function is only applicable to array having scalar values. for objects like element I think I need to implement deep copy to prevent mutating original array.

### CODE REVIEW

**Comment by Nirbhayparmar** [comment]
this is for issue #15

**Comment by Nirbhayparmar** [comment]
Please review the PR.

**Comment by Hetarth02** [comment]
I will soon be reviewing all the PRs(Probably by the end of coming Saturday and Sunday). Sorry for the wait.

**Comment by Nirbhayparmar** [comment]
No problem, Its okay.

**Review by Hetarth02 — APPROVED** [review]

**Pull request merged**
